### ISSUE TITLE
[feat] 수정사항

### ISSUE THREAD

**Issue by YuBeen-Park** [IN-SOPT-ANDROID/yubeen-park#5]
## 📝 todo
- [x] Hilt 적용
- [x] Enqueue 대신 코루틴 사용
- [x] Glide 대신 Coil 사용
- [x] 뷰 파일 함수명 통일
